messages:
  vip: "&7======&bVip Info&7======\n[informacje na temat rangi vip]"
  vipplus: "&7======&bVip+ Info&7======\n[informacje na temat rangi vip+]"
  svip: "&7======&bSvip Info&7======\n[informacje na temat rangi svip]"